// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://esfpjoovqmktbtjdxqox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzZnBqb292cW1rdGJ0amR4cW94Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDM4OTAsImV4cCI6MjA2NTUxOTg5MH0.mxKM5k5me82yByZ7lfDNpm736a-t5MVzGm823zRbAHk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);